export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALL_ALERTS = 'REMOVE_ALL_ALERTS';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';
export const DETAILS_FAILURE = 'DETAILS_FAILURE';
